report: indentation
Cytrus-RE/cytrus-re pull request #425
Opened 2020-10-01 06:46 UTC by Oxygemo

disgusting

2020-10-01 06:47 UTC, Rexogamer requested changes

2020-10-01 06:47 UTC, Rexogamer commented on src/commands/report.js
> +    // oops my pc crashed and i lost all my data, and i had an antivirus!
Remove this

2020-10-01 06:47 UTC, Oxygemo commented on src/commands/report.js
> +    // oops my pc crashed and i lost all my data, and i had an antivirus!
it's le funny but sure

2020-10-02 15:56 UTC, Rexogamer approved these changes
Gonna redo some of this command anyway but ye

2020-10-02 15:56 UTC, merged